[package]
name = "jailerctl"
version.workspace = true
edition = "2021"
description = "CLI for managing icb-sandbox"

[[bin]]
name = "icb-sandbox-ctl"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
nix = { version = "0.31", features = ["process", "signal", "feature"] }
serde = { workspace = true }
serde_json = { workspace = true }
